### ISSUE TITLE
Running dev server should automatically set VAULT_ADDR to http address

### ISSUE THREAD

**Issue by tallpauley** [hashicorp/docker-vault#10]
I would expect that if you run the docker container with no configuration, you would be able to immediately use the vault CLI to connect with the dev server inside the container, but I had to set **VAULT_ADDR** to the http address.

Or is this by design so it forces a developer to learn to change **VAULT_ADDR**?

**Comment by jefferai** [comment]
Most users don't use Vault CLI from within Docker, so this just isn't an issue. It's easy to change with env vars.
