### ISSUE TITLE
Why must /vault/config be owned by vault?

### ISSUE THREAD

**Issue by skrysmanski** [hashicorp/docker-vault#104]
First, sorry that this is more a question rather than a direct issue/complaint.

So my question is: 

> Why does the `docker-entrypint.sh` try to chown the directory `/vault/config`? Does vault write into this directory?

I'm host binding it as read-only and now the init script complains that it can't chown the directory.

For reference, here are the lines that do this:

https://github.com/hashicorp/docker-vault/blob/2d011f1191b9b201b312b7c81e62ef1c54f67710/0.X/docker-entrypoint.sh#L68-L71

**Comment by jefferai** [comment]
I'm not sure, but I think it's one of two possibilities (or both):

1) A sort of defense-in-depth against random users dropping config into the directory
2) Docker requested that behavior when evaluating it for `library`

**Comment by skrysmanski** [comment]
@jefferai Could you please explain in a little bit more detail what you mean by that?

> A sort of defense-in-depth against random users dropping config into the directory

Which "users" are we talking about here? Users in the container? Users on the docker host?

> Docker requested that behavior when evaluating it for library

What do you mean by `library`?

**Comment by rtlong** [comment]
@skrysmanski `library` refers to Docker Hub's name for the collection of Docker images which have no namespace (that is, you use this image by `docker pull vault` rather than `docker pull vault/vault` or something). If you look here, https://hub.docker.com/_/vault/ you can see that it mentions `library/vault` in a few places in the Quick References section. More info here: https://github.com/docker-library/official-images

**Comment by jefferai** [comment]
If someone wanted to PR updates (e.g. an env var that skips the behavior) feel free.

**Comment by beoSheep** [comment]
Issue could be with Selinux policies, try to run disabled or permissive mode.

**Comment by qvicksilver** [comment]
> If someone wanted to PR updates (e.g. an env var that skips the behavior) feel free.

#129

**Comment by BentCoder** [comment]
Any plans to merge PR created by @qvicksilver ?

**Comment by jasonodonnell** [comment]
Merged #129 , the `SKIP_CHOWN` env can be set to avoid the chown of the `/vault` directories at runtime.
