### ISSUE TITLE
0.11.0 is not usable on linux 64

### ISSUE THREAD

**Issue by paolino** [hashicorp/docker-vault#107]
Step 1/17 : FROM vault:0.11.0                                                                           
0.11.0: Pulling from library/vault                                                                      
no matching manifest for linux/amd64 in the manifest list entries  
(crashing all deployment chain)

**Comment by clstb** [comment]
experiencing the same issue

**Comment by chrishoffman** [comment]
Filed an issue here https://github.com/docker-library/official-images/issues/4794.  They are usually pretty quick to respond to these.

**Comment by chrishoffman** [comment]
This has now been addressed manually by the docker team.  They are still working on this outstanding issue https://github.com/docker-library/official-images/issues/4789.
