### ISSUE TITLE
ERROR: no matching manifest for unknown in the manifest list entries

### ISSUE THREAD

**Issue by alexwwang** [hashicorp/docker-vault#108]
I met this error when trying to pull vault from docker hub.

I am not sure maybe this issue should be submitted to docker.

**Comment by chrishoffman** [comment]
Tracking with #107

**Comment by juderegys** [comment]
I am trying to build docker and I keep getting the following. Any idea how to resolve?

Sending build context to Docker daemon  768.7MB
Step 1/26 : FROM docker.io/debian:9.4-slim
9.4-slim: Pulling from library/debian
no matching manifest for unknown in the manifest list entries

**Comment by jefferai** [comment]
Looks like an issue with Docker...

**Comment by alexwwang** [comment]
Hi,

You may git clone the original docker code to your local to build your own,
or fork one in within and build it automatically with your docker hub
account.

Then you could use your own fork edition of it. I've tested this way.

**Comment by Krishnaarunangsu** [comment]
I am also facing the issue in Windows 10:
Sending build context to Docker daemon  5.672MB
Step 1/1 : FROM tomcat:8-jre8
8-jre8: Pulling from library/tomcat
no matching manifest for unknown in the manifest list entries

**Comment by juderegys** [comment]
In my case, I had used 'Windows containers' when I had the issue. After switching to 'Linux containers', the error went away. You can try this is you have the same scenario.

**Comment by Michael501** [comment]
I am having the same problem

PS C:\Users\micha> docker pull mysql
Using default tag: latest
latest: Pulling from library/mysql
no matching manifest for unknown in the manifest list entries
PS C:\Users\micha>

Is switching to Linux the only answer

**Comment by chrishoffman** [comment]
@Michael501 We don't have experience building Linux containers but PRs are welcome!

**Comment by Michael501** [comment]
Hi,

Sorry I don't know what a PR is, if it is something to do with helping on the project then I am afraid my skillset is way short of that position.
What I meant was in the short to mid term is using Docker on a Linux OS the answer, I would much prefer Docker on Windows but I need a quick fix to a problem.

Cheers
Michael Collins
________________________________

**Comment by Fectorez** [comment]
On Windows
- Right click Docker instance
-List item
-Go to Settings
-Daemon
-Advanced
-Set the "experimental": true

Found on [https://stackoverflow.com/questions/48066994/docker-no-matching-manifest-for-windows-amd64-in-the-manifest-list-entries](url)

**Comment by eyosias-et** [comment]
On windows 10 with latest Docker using windows containers.
setting experimental flag worked.
