### ISSUE TITLE
Starting Vault (Hashicorp vault) in docker container on AWS EC2

### ISSUE THREAD

**Issue by weisinc** [hashicorp/docker-vault#11]
I have been trying to start hashicorp vault in a docker container connecting to file backend. The docker images was created but I can't run it. I kept getting error with the config file not found. Any help is most appreciated.

docker run -p 8200:8200 --name vault -e 'VAULT_DEV_ROOT_TOKEN_ID=' -e 'VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200' vault server -config=file.hcl

Error loading configuration from file.hcl: stat file.hcl: no such file or directory

file.hcl :
backend "file" {
    path = "sfiles"
}
listener "tcp" {
    address = "0.0.0.0:8200"
    tls_disable = 1
}
disable_mlock=true

**Comment by weisinc** [comment]
I decided to put the configuration on the command line while starting the docker image.

docker run -d -p 8200:8200 --name=vault --cap-add=IPC_LOCK -e 'VAULT_DEV_ROOT_TOKEN_ID=' -e 'VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200' -e 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/home/ec2-user/sfiles"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}' vault server

With this i was able to start vault in the docker container.  However, I am not able to reach port 8200.  Does anyone have any thoughts? perhaps the ip/port mapping is wrong, or taking the default..?

**Comment by DennyLoko** [comment]
How are you trying to connect to vault server? Which error are you getting? Please share more information, then we can help you.

**Comment by jefferai** [comment]
Closing due to lack of response.
