### ISSUE TITLE
vault images don't contain license files

### ISSUE THREAD

**Issue by anonymouse64** [hashicorp/docker-vault#113]
For example, the `vault:0.11.1` and `vault:0.10.2` images don't contain the corresponding license file for vault (i.e. the one from : https://github.com/hashicorp/vault/blob/master/LICENSE)

**Comment by jefferai** [comment]
I've never noticed license files in docker containers. Usually it's linked from the Hub. Is this a normal practice?

**Comment by anonymouse64** [comment]
I'm not a lawyer, but the MIT license says:

> The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

I'm pretty sure a docker image still counts as a copy of the software.

**Comment by chrishoffman** [comment]
I believe this is related to the source code not the binary distribution.  I looked at some other big docker project and I also don't see including the license file.
