### ISSUE TITLE
Dev params still passed to vault in prod mode

### ISSUE THREAD

**Issue by mafrosis** [hashicorp/docker-vault#114]
Hi, I just noticed our production Vault process looks like this in top:

    vault server -config=/vault/config -dev-root-token-id= -dev-listen-address=0.0.0.0:8200

Which is defined in `docker-entrypoint.sh` at https://github.com/hashicorp/docker-vault/blob/master/0.X/docker-entrypoint.sh#L55

Is it correct that `-dev*` params are used in production? At the very least this _looks_ wrong.

**Comment by Ginja** [comment]
Noticed this as well, and came here to ask.

**Comment by jefferai** [comment]
The parameters don't do anything if `-dev` is not specified. (In your logs you should see `You cannot specify a custom root token ID outside of "dev" mode. Your request has been ignored.`)

**Comment by TimoKramer** [comment]
That is still a problem. You should not ignore this.
```
/ # sh -x /usr/local/bin/docker-entrypoint.sh server -config=/vault/config/vault.hcl
+ set -e
+ '[' -n  ]
+ '[' -n  ]
+ VAULT_CONFIG_DIR=/vault/config
+ '[' -n  ]
+ '[' s '=' - ]
+ '[' server '=' server ]
+ shift
+ set -- vault server '-config=/vault/config' '-dev-root-token-id=' '-dev-listen-address=0.0.0.0:8200' '-config=/vault/config/vault.hcl'
+ '[' vault '=' vault ]
+ stat -c '%u' /vault/config
+ id -u vault
+ '[' 100 '!=' 100 ]
+ stat -c '%u' /vault/logs
+ id -u vault
+ '[' 100 '!=' 100 ]
+ stat -c '%u' /vault/file
+ id -u vault
+ '[' 100 '!=' 100 ]
+ '[' -z  ]
+ which vault
+ readlink -f /bin/vault
+ setcap 'cap_ipc_lock=+ep' /bin/vault
+ vault -version
+ id -u
+ '[' 0 '=' 0 ]
+ set -- su-exec vault vault server '-config=/vault/config' '-dev-root-token-id=' '-dev-listen-address=0.0.0.0:8200' '-config=/vault/config/vault.hcl'
+ exec su-exec vault vault server '-config=/vault/config' '-dev-root-token-id=' '-dev-listen-address=0.0.0.0:8200' '-config=/vault/config/vault.hcl'
```
Cost me quite some time to debug the bind-error.

**Comment by jefferai** [comment]
What version of Vault are you using?

**Comment by TimoKramer** [comment]
Hi, I am using vault 1.0.2. In the [docker-entrypoint.sh line 50](https://github.com/hashicorp/docker-vault/blob/c9a1e0087e0e91c1c276290ef34950f81cb7174e/0.X/docker-entrypoint.sh#L50), there it is tested  if you start vault with `server` param. But if it is started with `server` there should not be the params `-dev-root-token-id` and `-dev-listen-address` because you don't want to have dev-mode but production mode.
Or do I get it wrong?

**Comment by jefferai** [comment]
We specifically put in code -- see https://github.com/hashicorp/vault/blob/master/command/server.go#L372 and https://github.com/hashicorp/vault/blob/master/command/server.go#L387 -- so that passing these but not also passing `-dev` should have no effect.

**Comment by bigbellyburger** [comment]
@jefferai I'm not seeing those log lines in my log and no root token seems to be used
