### ISSUE TITLE
Docker build

### ISSUE THREAD

**Issue by juderegys** [hashicorp/docker-vault#117]
Hello,
I am trying to build docker and I keep getting the following. Any idea how to resolve?

Sending build context to Docker daemon 768.7MB
Step 1/26 : FROM docker.io/debian:9.4-slim
9.4-slim: Pulling from library/debian
no matching manifest for unknown in the manifest list entries

I am running this on Windows 10.

**Comment by chrishoffman** [comment]
We don't really have experience with building Windows containers but PRs are welcome.
