### ISSUE TITLE
Docker-vault on Openshift

### ISSUE THREAD

**Issue by paulohleal** [hashicorp/docker-vault#12]
I am trying to run the docker-vault on Openshift but by default it does not allow me to run a container as a root. I believe this is causing the error:
`/usr/local/bin/docker-entrypoint.sh: line 18: can't create /vault/config/local.json: Permission denied`
Is it possible to change the files and folders permissions so we can run it as an "ordinary" user?

As an another issue (if it is the case I can create another one) I changed the Openshift configurations in order to run the container as root, but I got the following error:
`Error loading configuration from /vault/config: Error loading /vault/config/local.json: At -: root.disable_mlock: unknown type *ast.LiteralType`

The command I used to create an application in both cases was:
`oc new-app vault 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h", "disable_mlock": "true"}'`

Thanks in advance,

**Comment by jefferai** [comment]
See #5 regarding your first question.

For the second, disable_mlock should be true, not "true".

**Comment by get2arun** [comment]
i had the same issue at line 43. From code, the error is at line in [url](https://github.com/hashicorp/docker-vault/blob/master/0.X/docker-entrypoint.sh) 
~/github/hashitvault$ oc logs pod/vault-69f47575bb-jf9qm
/usr/local/bin/docker-entrypoint.sh: line 43: can't create /vault/config/local.json: Permission denied

executing the below command fixed the issue. Not sure whether this is related to serviceaccount permission.
$oc adm policy add-scc-to-user anyuid -z vault-auth
scc "anyuid" added to: ["system:serviceaccount:vault-demo:vault-auth"]
