### ISSUE TITLE
Can't start image 0.11.5

### ISSUE THREAD

**Issue by sergey-morenets** [hashicorp/docker-vault#121]
Hi

I use Docker 18.09 on Windows 10 and tried to run Vault image using standard command:

`docker run --cap-add=IPC_LOCK -it -p 8200:8200 vault `

It gave me an error message in the log:

`Couldn't start vault with IPC_LOCK. Disabling IPC_LOCK, please use --privileged or --cap-add IPC_LOCK`

I tried additional commands suggested in other topics but none of them succeeded:

```
docker run --cap-add=IPC_LOCK -d -p 8200:8200 -e SKIP_SETCAP=true vault 
docker run --cap-add=IPC_LOCK -d -p 8200:8200 --privileged vault 
docker run --cap-add=IPC_LOCK -d -p 8200:8200 -e 'VAULT_LOCAL_CONFIG={"disable_mlock: true"} vault 
```

My storage driver according to docker info command seems ok (overlay2):

```
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
```

Can you please help?

**Comment by nukeu666** [comment]
This is more of a warning rather than error
Vault will still startup and work normally
If it is a first run, you need to 'vault operator init'

**Comment by endofcake** [comment]
@sergey-morenets , have you tried passing `{"disable_mlock: true"}` as a config file rather than environment variable?

**Comment by sergey-morenets** [comment]
@endofcake Hi, I tried to run this command:
docker run --cap-add=IPC_LOCK -it -p 8200:8200 -e 'VAULT_LOCAL_CONFIG={"disable_mlock: true"}' vault 

But I still got exception:

Couldn't start vault with IPC_LOCK. Disabling IPC_LOCK, please use --privileged or --cap-add IPC_LOCK

**Comment by sergey-morenets** [comment]
@endofcake I just realized that you meant using configuration file. But how can I supply it to Docker image?

**Comment by jefferai** [comment]
Closing due to lack of response.
