### ISSUE TITLE
Add environment for -dev-kv-v1

### ISSUE THREAD

**Issue by arossert** [hashicorp/docker-vault#136]
Following [#5919](https://github.com/hashicorp/vault/pull/5919) Vault is now supported with `-dev-kv-v1` to enable the `v1` for development, can you add an environment variable for the docker container to start it with this flag?

Will be glad to create a PR if you give me some pointers on how to do this.

**Comment by jefferai** [comment]
The server command honors passed-in arguments so simply pass it in as an argument when launching the container.

**Comment by arossert** [comment]
@jefferai thanks, didn't know about that.
