### ISSUE TITLE
Can not longer mount /vault/config

### ISSUE THREAD

**Issue by rmb938** [hashicorp/docker-vault#15]
#13 no longer allows using bind volume mounts for ```/vault```

When starting a container with ```/vault/config``` mounted the following error is given:

```
chown: /vault/config/vault.hcl: Operation not permitted
chown: /vault/config: Operation not permitted
chown: /vault/config: Operation not permitted
```

The docs do recommend using the environment variable ```VAULT_LOCAL_CONFIG``` but that is not always the best solution when trying to use complex configuration.

**Comment by jefferai** [comment]
That's strange; the chown is running as root, so shouldn't have an issue...Any chance you can try debugging on your setup?

**Comment by rmb938** [comment]
Hmm well digging into it some more it seems that it isn't running even with nothing mounted.

```
docker run vault:latest
```

just returns ```error: exec failed: operation not permitted``` That seems to happen on both docker-machine and docker for mac. 

But running 0.6.2 seems to be working fine

```
docker run vault:0.6.2
```

**Comment by jefferai** [comment]
You need to either disable mlock in your config or use `--cap-add=IPC_LOCK`

**Comment by rmb938** [comment]
Hmm well when I give it a config that has mlock disabled it returns the chown error on docker-machine. On Docker for Mac and a Centos 7 linux machine it returns the exec failed error.

**Comment by hamstah** [comment]
Hi,
Ran into the same issue with 0.6.4 and docker-compose.
After adding IPC_LOCK to cap_add the container starts but fails to start if there is another container for vault (ie not cleaned up properly with docker-compose down).

```
error: exec failed: text file busy
```

```yaml
  vault:
    image: "vault:0.6.4"
    cap_add:
      - IPC_LOCK
```

Since IPC_LOCK is now required to run vault, shouldn't this be considered a backward incompatible change and be reflected in the version number?

**Comment by hamstah** [comment]
Hmm I guess the issue is that it's not a breaking change for vault itself, only the docker image.

**Comment by jefferai** [comment]
Vault will fall back in the next iteration of the containers.
