### ISSUE TITLE
Remove compulsory declaration of `secret/*` for new policies

### ISSUE THREAD

**Issue by BentCoder** [hashicorp/docker-vault#151]
Hi,

I hope I am doing things wrong but this is what I gathered so far.

**Is your feature request related to a problem? Please describe.**
It is a kind of problem but more like user experience problem. If I create a new policy I have to allow, at least, "list" access to `secret/*` path otherwise new policy cannot navigate to its own path `secret/staging` at all. All I would see is "Not Authorized. You don't have access to secret/.". To solve such issue, I have to use policy below.

```json
{
  "path": {
    "secret/*": {
      "capabilities": ["list"]
    }
  },
  "path": {
    "secret/staging/*": {
      "capabilities": ["create", "read", "update", "delete", "list"]
    }
  }
}
```

Although this solves the issue, my new policy can now list everything under `secret` path. It has many more paths and secret names. I can currently see paths below and the secrets inside:
- secret/staging (_only this is relevant to me and I don't want to see the ones below_)
- secret/production
- secret/test

**Describe the solution you'd like**
New policy should not be forced to declare `path:secret/*:capabilities` block.

**Comment by jasonodonnell** [comment]
Hi @BentCoder!

This is not really a `docker-vault` issue but more of a general `vault` question.  You can get more feedback if you reopen the issue in the [Vault project](https://github.com/hashicorp/vault).

Sorry for the delay but hope that helps!
