### ISSUE TITLE
vault:latest fails, possibly due to bad setcap call in docker-entrypoint.sh

### ISSUE THREAD

**Issue by y0ssar1an** [hashicorp/docker-vault#16]
#### Steps to Reproduce
```sh
$ docker run -d --name=dev-vault vault
6b46031c562b6935d80f4e8336fdeb7d90e5795bfb1aee29243a24e369a6616f
$ aws docker logs dev-vault
error: exec failed: operation not permitted
```
#### Version Info
docker version: docker for mac 1.12.3
image: `vault:latest`

#### Additional Info
The Apcera platform, which also runs Docker containers, points the finger at `setcap()`.
```
Failed to set capabilities on file `/bin/vault' (Operation not permitted)
usage: setcap [-q] [-v] (-r|-|<caps>) <filename> [ ... (-r|-|<capsN>) <filenameN> ]
Note <filename> must be a regular (non-symlink) file.
```

**Comment by jefferai** [comment]
See the docs on Hub; you need to add in `--cap-add=IPC_LOCK` when doing your `docker run`.

**Comment by y0ssar1an** [comment]
Thank you for the quick reply! I think we should add `--cap-add=IPC_LOCK` to the [README here](https://github.com/docker-library/docs/blob/master/vault/README.md#running-vault-for-development) to prevent confusion.
```sh
$ docker run -d --name=dev-vault --cap-add=IPC_LOCK vault
```

**Comment by jefferai** [comment]
There's already a PR in for it . :-D
