### ISSUE TITLE
Need curl installed in the docker-vault image

### ISSUE THREAD

**Issue by induja0107** [hashicorp/docker-vault#168]
Hi, 

Can you please install curl in the docker image so i can use it for health checks. I see that consul from 0.7 comes with curl installed, so it would be great to have curl installed in vault too, thanks!

**Comment by mterron** [comment]
Can't you just use a HTTP or TCP check? 
You can also extend the image and add whatever tools you need for your specific use case

**Comment by chrishoffman** [comment]
Thanks for the suggestion.  We removed curl some time ago to limit the the security surface area of the image.  As @mterron suggested, feel free to extend this image with additional tools and resources.
