### ISSUE TITLE
vault can no longer be started without escalated privileges

### ISSUE THREAD

**Issue by ColinHebert** [hashicorp/docker-vault#17]
Since the addition of this snippet:

```bash
# Allow mlock to avoid swapping Vault memory to disk
setcap cap_ipc_lock=+ep $(readlink -f $(which vault))
```

Vault can't be started without having to obtain privileges. Which means that the container can't be used for any operation that doesn't interact with the memory at all (using it as a client for example) without being able to do IPC_LOCK.

The good part is that the entrypoint script might offer a solution. If we can detect whether or not the `vault` executable is indeed still executable after the `setcap`, we should be able to revert the `setcap` (with a big warning saying that IPC_LOCK isn't available within the container).

If the automatic detection isn't good enough of a solution, we could have an env variable which, if set, prevents the setcap from being executed in the first place.

My preference would be for the first option as it makes it easier to people to use (instead of failing, trying to understand why the vault executable stopped working, etc.), but the second one would work as well.

**Comment by jefferai** [comment]
Which version of the Vault container are you using?

**Comment by ColinHebert** [comment]
I'm using the version tagged with 0.6.4, but this has been introduced with 1.6.3

**Comment by jefferai** [comment]
@ColinHebert  If you can build the container locally, can you try the current code on your problematic  system with setting the `SKIP_SETCAP` env var non-empty and see if this bypasses the problem for you?
