### ISSUE TITLE
Start container with `userpass` auth enabled

### ISSUE THREAD

**Issue by mmoravcik** [hashicorp/docker-vault#172]
👋 is there any way to spin up the container with docker-compose with "userpass" enabled and also with some default pre-created user?

At the moment I can only auth with the container with a token set in `VAULT_DEV_ROOT_TOKEN_ID` env variable.

**Comment by chrishoffman** [comment]
There is currently no way to provide default set of data to Vault.  Usually users provide a script to bootstrap the data or leverage Terraform to provide an initial set of configuration.

**Comment by mmoravcik** [comment]
Hi @chrishoffman do you have any example of such script? Basically, are you saying that it is not currently possible to enable userpass on the startup?

**Comment by chrishoffman** [comment]
That's correct.  Since Vault requires all interactions to be authenticated and authorized, there is no "default" set of values that you can provide on startup.  Many people just leverage the Vault CLI in a shell script with an order of commands with the appropriate token provided.

**Comment by mmoravcik** [comment]
Thank you,  is there any example of such script? I could not find any :(

**Comment by chrishoffman** [comment]
Something like this would be an example https://gist.github.com/chrishoffman/acc60cf577e1e79f56beb63747466d3c.  You'll need to set the token using the `VAULT_TOKEN` environment variable.
