### ISSUE TITLE
/vault/file is no longer readable by vault

### ISSUE THREAD

**Issue by bmitch3020** [hashicorp/docker-vault#20]
With the update 0.6.3 to run vault as the user vault, files in a volume under /vault/file (and likely /vault/logs) are no longer readable or writable by the vault user. This results in errors attempting to start vault referencing "failed to read seal configuration: error=open /vault/file/core/_seal-config: permission denied".

This can be reproduced by running:

```
$ mkdir config-test
$ cat >config-test/local.json <<EOF
{
  "disable_mlock": true,
  "default_lease_ttl": "168h",
  "max_lease_ttl": "2160h",
  "backend": {"file": {"path":"/vault/file"}},
  "listener": {
    "tcp": {
      "address": "0.0.0.0:8200",
      "tls_disable": "true"
    }
  }
}
EOF
$ docker run -d -v vault-test:/vault/file -v `pwd`/config-test:/vault/config:ro --name vault-test vault:0.6.2 server
$ docker exec -it vault-test vault init -address=http://127.0.0.1:8200
$ docker stop vault-test
$ docker rm vault-test
$ docker run -d -v vault-test:/vault/file -v `pwd`/config-test:/vault/config:ro --name vault-test vault:0.6.4 server
$ docker logs vault-test # see error from /vault/config being read only
$ docker rm vault-test
$ docker run -d -v vault-test:/vault/file -v `pwd`/config-test:/vault/config --name vault-test vault:0.6.4 server
$ docker logs vault-test # see operation not permitted error from missing IPC_LOCK capability
$ docker rm vault-test
$ docker run -d -v vault-test:/vault/file -v `pwd`/config-test:/vault/config --name vault-test --cap-add=IPC_LOCK vault:0.6.4 server
$ docker exec -it vault-test vault status -address=http://127.0.0.1:8200 # see error from /vault/file/core/_seal-config: permission denied
```

I'd like to see support for read only config volumes return, it shouldn't matter who owns these files as long as they can be read by the vault user. But more importantly, files in /vault/file and /vault/log should have their ownership adjusted

**Comment by jefferai** [comment]
It's funny, I took those out because of complaints about the exact opposite, that Vault shouldn't be adjusting ownership and perms of items bound mount in.

**Comment by bmitch3020** [comment]
They do have a good point, though I'd say any folder that is written to by Vault should be fair game to change permissions in. Best would have been to make a change like this as a major version, but hindsight is 20:20. I'm not a fan of images that don't upgrade cleanly, so I'm pushing for a transparent fix, but a note in the readme about upgrade issues users may encounter and recommended solutions may help.

**Comment by jefferai** [comment]
> Best would have been to make a change like this as a major version

This isn't a change to Vault...

**Comment by jefferai** [comment]
PR is in for a change to Hub version that will address this.
