### ISSUE TITLE
Unable to build image using version 1.7.1:wget: server returned error: HTTP/1.1 403 Forbidden

### ISSUE THREAD

**Issue by anudeep-modak** [hashicorp/docker-vault#224]
`+ cd /tmp/build
+ wget https://releases.hashicorp.com/vault/1.7.1/vault_1.7.1_linux_amd64.zip
Connecting to releases.hashicorp.com (151.101.153.183:443)
saving to 'vault_1.7.1_linux_amd64.zip'
vault_1.7.1_linux_am   4% |*                               | 3262k  0:00:19 ETA
vault_1.7.1_linux_am  23% |*******                         | 15.2M  0:00:06 ETA
vault_1.7.1_linux_am  50% |****************                | 33.4M  0:00:02 ETA
vault_1.7.1_linux_am  60% |*******************             | 39.5M  0:00:02 ETA
vault_1.7.1_linux_am  84% |**************************      | 55.3M  0:00:00 ETA
vault_1.7.1_linux_am 100% |********************************| 65.6M  0:00:00 ETA
'vault_1.7.1_linux_amd64.zip' saved
+ wget https://releases.hashicorp.com/vault/1.7.1/vault_1.7.1_SHA256SUMS
Connecting to releases.hashicorp.com (151.101.153.183:443)
saving to 'vault_1.7.1_SHA256SUMS'
vault_1.7.1_SHA256SU 100% |********************************|  1415  0:00:00 ETA
'vault_1.7.1_SHA256SUMS' saved
+ wget https://releases.hashicorp.com/vault/1.7.1/vault_1.7.1_SHA256SUMS.sig
Connecting to releases.hashicorp.com (151.101.153.183:443)
wget: server returned error: HTTP/1.1 403 Forbidden
The command '/bin/sh -c set -eux;     apk add --no-cache ca-certificates gnupg openssl libcap su-exec dumb-init tzdata &&     apkArch="$(apk --print-arch)";     case "$apkArch" in         armhf) ARCH='arm' ;;         aarch64) ARCH='arm64' ;;         x86_64) ARCH='amd64' ;;         x86) ARCH='386' ;;         *) echo >&2 "error: unsupported architecture: $apkArch"; exit 1 ;;     esac &&     VAULT_GPGKEY=91A6E7F85D05C65630BEF18951852D87348FFC4C;     found='';     for server in         hkp://p80.pool.sks-keyservers.net:80         hkp://keyserver.ubuntu.com:80         hkp://pgp.mit.edu:80     ; do         echo "Fetching GPG key $VAULT_GPGKEY from $server";         gpg --batch --keyserver "$server" --recv-keys "$VAULT_GPGKEY" && found=yes && break;     done;     test -z "$found" && echo >&2 "error: failed to fetch GPG key $VAULT_GPGKEY" && exit 1;     mkdir -p /tmp/build &&     cd /tmp/build &&     wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_${ARCH}.zip &&     wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_SHA256SUMS &&     wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_SHA256SUMS.sig &&     gpg --batch --verify vault_${VAULT_VERSION}_SHA256SUMS.sig vault_${VAULT_VERSION}_SHA256SUMS &&     grep vault_${VAULT_VERSION}_linux_${ARCH}.zip vault_${VAULT_VERSION}_SHA256SUMS | sha256sum -c &&     unzip -d /bin vault_${VAULT_VERSION}_linux_${ARCH}.zip &&     cd /tmp &&     rm -rf /tmp/build &&     gpgconf --kill dirmngr &&     gpgconf --kill gpg-agent &&     apk del gnupg openssl &&     rm -rf /root/.gnupg' returned a non-zero code: 1
`

**Comment by anudeep-modak** [comment]
node@node1 test]$ wget https://releases.hashicorp.com/vault/1.7.1/vault_1.7.1_SHA256SUMS.sig
--2021-04-23 20:56:12--  https://releases.hashicorp.com/vault/1.7.1/vault_1.7.1_SHA256SUMS.sig
Resolving releases.hashicorp.com (releases.hashicorp.com)... 151.101.153.183, 2a04:4e42:24::439
Connecting to releases.hashicorp.com (releases.hashicorp.com)|151.101.153.183|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-04-23 20:56:13 ERROR 403: Forbidden.

**Comment by a-riva** [comment]
[The GPG signing key was rotated](https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512)

**Comment by anudeep-modak** [comment]
Thanks a lot @a-riva .It worked!!!
