### ISSUE TITLE
Vault docker image disabling IPC_LOCK

### ISSUE THREAD

**Issue by michelvocks** [hashicorp/docker-vault#24]
```
docker --version
Docker version 1.12.5, build 7392c3b
```

```
vault --version
Vault v0.6.4 ('f4adc7fa960ed8e828f94bc6785bcdbae8d1b263')
```

`docker run --cap-add=IPC_LOCK -d --name=dev-vault vault`
```
docker logs dev-vault
Couldn't start vault with IPC_LOCK. Disabling IPC_LOCK, please use --privileged or --cap-add IPC_LOCK
error: exec failed: text file busy
```

```
root@ip-10-52-140-72:~# docker info
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952 GiB
Name: ip-10-52-140-72
ID: 4C2S:V7AN:A6VX:27EW:G4BI:5FQD:XZN4:U3UD:QOWS:MJJ3:G4C5:6OIY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by jefferai** [comment]
I believe this might be related to using the aufs storage driver; can you try overlayfs or devicemapper and see if that fixes it?

**Comment by michelvocks** [comment]
Thanks @jefferai 
You were right.

**Comment by hipadmin** [comment]
just curious whether using overlayfs (or overlayfs2?) is the only solution?! the docker docs state that "caution should be taken before using it in production", given that it's relatively immature. I'm a little reluctant to switch all of our other prod docker containers to use overlay as well, which I would have to...

**Comment by jefferai** [comment]
SKIP_SETCAP should work, are you using the 0.6.5 container?

**Comment by hipadmin** [comment]
Set the env variables incorrectly for SKIP_SETCAP. that did indeed work.

**Comment by denizarman** [comment]
Hi jefferai
You said 
> I believe this might be related to using the aufs storage driver; can you try overlayfs or devicemapper and see if that fixes it?
Can you explain steps for those who experienced same?
Thanks a lot

**Comment by jefferai** [comment]
@denizarman  the steps are two posts above :-) Use SKIP_SETCAP with the 0.6.5 container.

**Comment by memotype** [comment]
Can someone tell me how to "use SKIP_SETCAP"? Is it an argument to the "docker run" command?

**Comment by memotype** [comment]
Nevermind, I figured it out. When I set SKIP_SETCAP, I get a different error:

```
ubuntu@svs-vault:~/vault-docker/vault$ sudo docker run -e SKIP_SETCAP=true --name vaultc -v $PWD:/vault --expose 8200 --cap-add IPC_LOCK vault server
Error initializing core: Failed to lock memory: cannot allocate memory

This usually means that the mlock syscall is not available.
Vault uses mlock to prevent memory from being swapped to
disk. This requires root privileges as well as a machine
that supports mlock. Please enable mlock on your system or
disable Vault from using it. To disable Vault from using it,
set the `disable_mlock` configuration option in your configuration
file.```

**Comment by bjay27** [comment]
still issue open????????????

**Comment by devinbost** [comment]
We still get the issue even with using `overlay2` as the storage driver.

**Comment by bjd2385** [comment]
The following worked for me, in case anyone else comes across this ~
```
docker run --restart=always --name vault -e 'SKIP_SETCAP=true' -e 'VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:1100' -e 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl":
"720h", "disable_mlock": true}' -p 1100:1100 vault:latest server
```
Everything's just set to defaults. I'm running this at home, however, not in Prod; I'd probably look at switching to `overlay2` if I could in Prod, as stated above.
