### ISSUE TITLE
No AMD64 version published for 1.9

### ISSUE THREAD

**Issue by artamonovkirill** [hashicorp/docker-vault#247]
On [Docker Hub](https://hub.docker.com/_/vault?tab=tags), 386, ARM and ARM64 SHAs are the same for `latest` and `1.9.0` tags, AMD64 is only available for `latest`.
[This SHA](https://hub.docker.com/layers/vault/library/vault/latest/images/sha256-895c58cd8301616b7c1cc1f6a249c6981443c82bfd237fec2981aa025198d409?context=explore) is tagged as `latest`, but not as `1.9.0`.

<img width="604" alt="Screenshot 2021-11-18 at 15 39 08" src="https://user-images.githubusercontent.com/2599636/142436281-60517303-0df9-4c81-948e-9217b6fe8b3c.png">

**Comment by mladlow** [comment]
Hi @artamonovkirill , thanks for flagging this. I'm taking a look.

**Comment by mladlow** [comment]
It looks like the official image that will be available here (https://hub.docker.com/_/vault?tab=tags) is still building. Official images we've built are available here: https://hub.docker.com/r/hashicorp/vault/tags. This link contains the full set of os/arch combinations for both the `latest` and `1.9.0` tags.

I'll come back and close this once the build is complete, but if anyone needs a docker image **right now**, you can get an official image from https://hub.docker.com/r/hashicorp/vault/tags.

**Comment by briantist** [comment]
any idea when the one _marked_ official will finish building? It seems strange that it's taking so long. Where can we see the progress?

**Comment by artamonovkirill** [comment]
> It looks like the official image that will be available here (https://hub.docker.com/_/vault?tab=tags) is still building. Official images we've built are available here: https://hub.docker.com/r/hashicorp/vault/tags. This link contains the full set of os/arch combinations for both the `latest` and `1.9.0` tags.

@mladlow thanks for looking into it. I'm surprised it takes a while to build. Since for 3 platforms that are available for `1.9.0`, SHAs are the same as for `latest`, I would expect no building involved, just adding a `1.9.0` tag to `895c58cd8301`, which is already uploaded to Docker Hub.

**Comment by briantist** [comment]
> > It looks like the official image that will be available here (https://hub.docker.com/_/vault?tab=tags) is still building. Official images we've built are available here: https://hub.docker.com/r/hashicorp/vault/tags. This link contains the full set of os/arch combinations for both the `latest` and `1.9.0` tags.
> 
> thanks for looking into it. I'm surprised it takes a while to build. Since for 3 platforms that are available for `1.9.0`, SHAs are the same as for `latest`, I would expect no building involved, just adding a `1.9.0` tag to `895c58cd8301`, which is already uploaded to Docker Hub.

@artamonovkirill  The `latest` tag for linux/amd64 is still using 1.8.5 though: https://hub.docker.com/layers/vault/library/vault/latest/images/sha256-895c58cd8301616b7c1cc1f6a249c6981443c82bfd237fec2981aa025198d409?context=explore

![image](https://user-images.githubusercontent.com/1260690/142489160-885c67bb-b9ef-454b-b6e0-e63f4e9efe5a.png)

**Comment by bhoriuchi** [comment]
looks like its working now
