### ISSUE TITLE
Consul backend on macOS

### ISSUE THREAD

**Issue by onetwopunch** [hashicorp/docker-vault#25]
I'm fairly new to Docker so I'm confident I'm making some dumb mistakes, but I wanted to setup the vault container with a docker consul cluster. My goal eventually is to setup one instance of vault (for now) and 3 instances of consul with 1 client node. 

Just to get things up and running, the vault config looks like:

```
# config/local.hcl
backend "consul" {
  address = "172.17.0.5:8500"
  scheme = "http"
  tls_skip_verify = 1
}

listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = 1
}
```

Then my docker startup script looks like this:

```
docker run -d --name consul1 -h consul1 consul agent -server -bootstrap-expect 3
JOIN_IP=$(docker inspect -f '{{.NetworkSettings.IPAddress}}' consul1)

docker run -d --name consul2 -h consul2 consul agent -server -retry-join $JOIN_IP
docker run -d --name consul3 -h consul3 consul agent -server -retry-join $JOIN_IP
docker run -d --name consul-client -h consul-client \
   -p 8500:8500 consul agent -client=0.0.0.0 -retry-join $JOIN_IP -ui

docker run -d -h vault --name vault -p 8200:8200 \
  --cap-add IPC_LOCK --link consul-client --volume $PWD/config:/vault/config \
  vault server
```

When I try to initialize vault, I get the following error:

```
$ vault init --key-shares=1 --key-threshold=1
Error initializing Vault: Put http://127.0.0.1:8200/v1/sys/init: EOF
```

To test out if I messed something up with the networking, I did the following:

```
$ docker exec -it vault /bin/sh
/ # apk add --no-cache curl
/ # curl http://172.17.0.5:8500/v1/status/peers
["172.17.0.2:8300","172.17.0.3:8300","172.17.0.4:8300"]
```

I also made sure that my localhost is listening on port 8200. 

```
$ lsof -i :8200
COMMAND    PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 2237 ryan   20u  IPv4 0xc9990e2d78428f6f      0t0  TCP *:trivnet1 (LISTEN)
com.docke 2237 ryan   23u  IPv6 0xc9990e2d77729b9f      0t0  TCP localhost:trivnet1 (LISTEN)
```

Which means (I think) that I linked the containers properly. I'm really confused why things aren't working and any help would be appreciated.

**Comment by jefferai** [comment]
What does 'docker logs' for the container say? Without seeing logs it's not possible to tell you the cause of the error.

**Comment by onetwopunch** [comment]
@jefferai The logs only show that vault has started successfully.

```
==> Vault server configuration:

                 Backend: consul (HA available)
                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
        Redirect Address: http://127.0.0.1:8200
                 Version: Vault v0.6.4
             Version Sha: f4adc7fa960ed8e828f94bc6785bcdbae8d1b263

==> Vault server started! Log data will stream in below:
```

And does not add anything when I use the vault command on the host.

**Comment by jefferai** [comment]
Looks like something is interfering with the connection to Vault then.

**Comment by onetwopunch** [comment]
@jefferai Figured it out. The issue was how I set up my vault listener I think. As soon as I configured the networks properly, it worked. I put it in a docker-compose as well: https://github.com/onetwopunch/vault
