### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by ns-cweber** [hashicorp/docker-vault#29]
The current image doesn't build on ARM. Is there any plan to support it?

**Comment by jefferai** [comment]
I imagine it's because it pulls in static binaries that are only amd64 right now.

**Comment by gligoran** [comment]
There are 2 amd64 binaries right now: docker-base and the vault itself. Docker-base only contain `dumb-init` and `gosu` both of which are available for arm. And vault also seems to have an arm build.

**Comment by jefferai** [comment]
I honestly don't know how one gets Docker Hub to build for different arches, but if someone is interested and wants to figure it out let me know.

**Comment by RihardsT** [comment]
Just wanted to say that I've been successfully building vault images for armhf by doing some sed commands [as seen here](https://github.com/RihardsT/cloud_project_infrastructure/blob/master/.gitlab-ci.yml#L79-L105), and I've pushed it [here](https://hub.docker.com/r/rihards/vault_arm/).
Could be improved, but so far seems to work great.

**Comment by chrishoffman** [comment]
ARM is now supported and available through Docker Hub. See #76.
