### ISSUE TITLE
Example Vault Listen Address Issue

### ISSUE THREAD

**Issue by tradesmanhelix** [hashicorp/docker-vault#30]
On the [Vault Docker Hub page](https://hub.docker.com/_/vault/), the example commands under "Running Vault for Development" this example listen address: 

`VAULT_DEV_LISTEN_ADDRESS=127.0.0.1:1234`

However, the 127.0.0.1 IP will _not_ work (tested on both Ubuntu 16.04 and MacOS Sierra) and will result in refused connections to the Vault container. Instead, users should use something like:

`VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:9999`

It's unfortunate that what was obviously intended to be an example port config is in fact invalid and will result in a number of obscure issues, none of which really hint at the underlying issue. Please update the page on Docker Hub to use this or a similar valid example for the VAULT_DEV_LISTEN_ADDRESS parameter.

Thank you!

**Comment by jefferai** [comment]
It depends on how you're running it; a lot of people using the Docker container for dev work aren't connecting from outside, but rather are using `vault` from within the running container itself to do testing. That's probably why nobody's complained about this before. (Also, the default listen address uses 0.0.0.0.)

**Comment by jefferai** [comment]
https://github.com/docker-library/docs/pull/844
