### ISSUE TITLE
Vault audit-enable on Windows Docker gives error

### ISSUE THREAD

**Issue by JonathonWei** [hashicorp/docker-vault#32]
I installed the Vault Docker on Windows.
When i run
```
docker exec <container name> vault audit-enable file file_path=/var/logs/vault_audit.log
```
It gives the following error
```
Error enabling audit backend: Error making API request.
URL: PUT http://127.0.0.1:8200/v1/sys/audit/file
Code: 400. Errors:
* missing client token
```

even when I run the vault audit enable inside the docker bash, it still gives me the same error. Does it mean all the CLI command get translated to a web request to API in VAULT docker? Any help will be appreciated.

**Comment by jefferai** [comment]
Hi @JonathonWei ,

All Vault calls require a valid token. It can be specified in the environment via VAULT_TOKEN, which is likely the right approach for what you're doing here.

**Comment by JonathonWei** [comment]
Hi @jefferai , I think my question is why the vault command line audit-enable will make the api call. It does not make sense to me.
