### ISSUE TITLE
Configuration Discrepancy

### ISSUE THREAD

**Issue by jwkuo** [hashicorp/docker-vault#35]
Comparing the documentation on the [Vault site](https://www.vaultproject.io/docs/configuration/index.html), configuring the storage backend for a server is inconsistent with this image. While this documentation hints at the key that works ("backend" as opposed to "storage"), the image does not seem to want to load and parse HCL files either. A few things I had to tweak to get it to work with JSON:
 - "storage" key is invalid. Had to use "backend" ("backend": {"consul": {}})
 - Does not parse boolean. Had to use 0 or 1 ("tls_skip_verify": 1)
 - Time does not recognize "d" as a unit. Had to convert to hours ("default_lease_ttl": "168h")

**Comment by jefferai** [comment]
The Vault site corresponds to the latest released version, which is 0.7. The Docker container is at 0.6.5, so does not contain these improvements.
