### ISSUE TITLE
Running vault as a user

### ISSUE THREAD

**Issue by RRAlex** [hashicorp/docker-vault#4]
Comparing Consul & Vault Dockerfiles, and their running containers, I noticed Vault didn't have its own user to drop the root privileges on start.

Is there a specific capability required by vault beside IPC_LOCK?
Could we simply use setcap on the filesystem or add_cap from docker as a work around to make the container more secure?

cheers!

**Comment by jefferai** [comment]
Maybe? I don't know much about it. If you can make mlock work in the container while using a non-root user, I'm happy to take a look and potentially merge it if it seems clean.

**Comment by jefferai** [comment]
(Closing in favor of #5)
