### ISSUE TITLE
Ability to enable Audit logs

### ISSUE THREAD

**Issue by adamgraves-choices** [hashicorp/docker-vault#46]
Hi,

It'd be nice if there was someway to enable the audit logs functionality and have that printed to stdout.

At the minute I can't figure out an easy way of using the log volume and monitoring the file, as well as rotating it.

**Comment by jefferai** [comment]
You can set the file to /dev/stdout!

**Comment by krish7919** [comment]
Sorry to resurrect an old thread, but wanted to update this with the docker image, I get `[ERROR] secrets.system.system_34b1e5dc: enable audit mount failed: path=file/ error="sanity check failed; unable to open "/dev/stdout" for writing: open /dev/stdout: permission denied"`
