### ISSUE TITLE
Disabling core dumps?

### ISSUE THREAD

**Issue by erickt** [hashicorp/docker-vault#50]
According to the [best practices guide](https://www.vaultproject.io/guides/production.html), Hashicorp is recommending that core dumps are disabled. Could this be (optionally?) added to this image?

**Comment by jefferai** [comment]
Go programs don't core dump by default. You have to explicitly enable them.

Outside of Go, any mechanism to disable core dumps is OS-specific, so there's nothing we can do at the Vault level.
