### ISSUE TITLE
push docker image 0.8.3 into docker hub

### ISSUE THREAD

**Issue by annapurnam** [hashicorp/docker-vault#55]
Description of the docker hub says it has image 0.8.3 (as latest) but that tag doesn't exist.
Someone forgot to push i believe

**Comment by chrishoffman** [comment]
We maintain the official repository but we don't control the push of the official images to docker hub. I see that it has since been published.

**Comment by annapurnam** [comment]
thanks for response.
Looks like it was published after this bug was created. It was published just 17 hours ago.
previously doc was updated but the actual image was not published.
I was able to pull image this morning.
