### ISSUE TITLE
issues with logging into container

### ISSUE THREAD

**Issue by Raghuveer123** [hashicorp/docker-vault#61]
when I try to log into the vault container, I am getting the following error...
I tried this command docker exec -it vault bash

rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"bash\\\": executable file not found in $PATH\"\n"

**Comment by jefferai** [comment]
Alpine Linux doesn't have bash. You need to use ash or sh instead.

**Comment by Raghuveer123** [comment]
Thanks...
