### ISSUE TITLE
issues in writing the secret file

### ISSUE THREAD

**Issue by Raghuveer123** [hashicorp/docker-vault#62]
I created Docker containers for vault when I tried the vault init...It shows the below error
* Vault is already initialized
/ # vault init
Error initializing Vault: Error making API request.

URL: PUT http://0.0.0.0:1234/v1/sys/init
Code: 400. Errors:
I cannot write the secret file...I will get the above the error....Can anyone help me with this issue?

**Comment by jefferai** [comment]
Once Vault is initialized you cannot initialize it again unless you wipe its data storage.
