### ISSUE TITLE
exec format error for custom plugins

### ISSUE THREAD

**Issue by Gabology** [hashicorp/docker-vault#65]
Attempting to enable the (vault-auth-example)[https://github.com/hashicorp/vault-auth-plugin-example] plugin on Docker vault image 0.8.3 results in the following error:

```
Error: Error making API request.

URL: POST http://127.0.0.1:8200/v1/sys/auth/example
Code: 400. Errors:

* fork/exec /vault/file/vault-plugins/vault-auth-example: exec format error
```

My configuration is:
```
VAULT_LOCAL_CONFIG='{ "plugin_directory": "/vault/file/vault-plugins" }'
```

And the plugin is bind mounted from the host into the directory, other than that there are no special parameters provided to the Docker host.

**Comment by jefferai** [comment]
Issue opened in other repo, closing here.
