### ISSUE TITLE
Confused on how to use in `server` mode

### ISSUE THREAD

**Issue by Sean-Brown** [hashicorp/docker-vault#72]
I was able to experiment with dev mode, but now I want a little persistence so I'm running the container in "server" mode, but I am unable to interact with the container. I added `"disable_mlock": true` to the local configuration, and after running the container it outputs:
```
Couldn't start vault with IPC_LOCK. Disabling IPC_LOCK, please use --privileged or --cap-add IPC_LOCK
==> Vault server configuration:

                     Cgo: disabled
               Log Level:
                   Mlock: supported: true, enabled: false
                 Storage: file
                 Version: Vault v0.9.1
             Version Sha: 87b6919dea55da61d7cd444b2442cabb8ede8ab1

==> Vault server started! Log data will stream in below:
```
It looks like it's running but now I am not sure how I am supposed to interact with this server. When running it in dev mode it tells you the vault token, so I am able to use that to authenticate with the cli. However, running in server mode it is unclear where this token is, how to generate this token and have vault use it, or even how to get started using vault. I've read the vault documentation, and I apologize for my newness, but it's unclear what the steps are to get this working. 

"Working", as in being able to execute commands against Vault. Currently I can shell into the container (as I did when it was in dev mode), but executing vault commands fails:
```
/ # vault auth-enable userpass
Error: Post https://127.0.0.1:8200/v1/sys/auth/userpass: dial tcp 127.0.0.1:8200: getsockopt: connection refused
/ # export VAULT_ADDR=http://127.0.0.1:8200
/ # vault auth-enable userpass
Error: Post http://127.0.0.1:8200/v1/sys/auth/userpass: dial tcp 127.0.0.1:8200: getsockopt: connection refused
/ # export VAULT_ADDR=http://0.0.0.0:8200
/ # vault auth-enable userpass
Error: Post http://0.0.0.0:8200/v1/sys/auth/userpass: dial tcp 0.0.0.0:8200: getsockopt: connection refused
```
I'm assuming the "connection refused" error is because I haven't authenticated, but I am not sure how I'm supposed to do this without knowing the token.

**Comment by tangopapa** [comment]
Having this exact issue after running:
docker run --cap-add=IPC_LOCK \
-e 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}' \
vault server.  That works. But after that, if I try to run something like:   

# docker exec -it 0b9xxxac7fee vault operator init
Error initializing: Put https://127.0.0.1:8200/v1/sys/init
# export VAULT_ADDR=http://127.0.0.1:8200
Error initializing: Put https://127.0.0.1:8200/v1/sys/init:
# export VAULT_ADDR=http://0.0.0.0:8200
Error initializing: Put https://127.0.0.1:8200/v1/sys/init:
# docker network inspect -f '{{range .Containers}}{{println .Name .IPv4Address}}{{end}}' bridge
172.17.0.3 vault internal eth0 address
# export VAULT_ADDR=http://172.17.0.3/:8200
Error initializing: Put https://127.0.0.1:8200/v1/sys/init:
I'm executing the export commands on the hosts, not in the containers.


Also I'm trying to get this to work w/ the progrium/consul docker backend:
docker run -p 8400:8400 -p 8500:8500 -p 8600:53/udp --hostname consul --name consul progrium/consul -server -bootstrap -ui-dir /ui.  This works fine.

If I want to include a config file to the docker run command above, is this the correct syntax?
docker run --cap-add=IPC_LOCK \
      --hostname vault \
      --name vault \
      --link consul:consul \
      vault server -config=/opt/config.hcl

**Comment by tangopapa** [comment]
Having this exact issue after running:
docker run --cap-add=IPC_LOCK 
-e 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}' 
vault server. That works. But after that, if I try to run something like:

docker exec -it 0b9xxxac7fee vault operator init
Error initializing: Put https://127.0.0.1:8200/v1/sys/init

export VAULT_ADDR=http://127.0.0.1:8200
Error initializing: Put https://127.0.0.1:8200/v1/sys/init:

export VAULT_ADDR=http://0.0.0.0:8200
Error initializing: Put https://127.0.0.1:8200/v1/sys/init:

docker network inspect -f '{{range .Containers}}{{println .Name .IPv4Address}}{{end}}' bridge
172.17.0.3 vault internal eth0 address

export VAULT_ADDR=http://172.17.0.3/:8200
Error initializing: Put https://127.0.0.1:8200/v1/sys/init:
I'm executing the export commands on the hosts, not in the containers.

Also I'm trying to get this to work w/ the progrium/consul docker backend:
docker run -p 8400:8400 -p 8500:8500 -p 8600:53/udp --hostname consul --name consul progrium/consul -server -bootstrap -ui-dir /ui. This works fine.

If I want to include a config file to the docker run command above, is this the correct syntax?
docker run --cap-add=IPC_LOCK 
--hostname vault 
--name vault 
--link consul:consul 
vault server -config=/opt/config.hcl

**Comment by Sean-Brown** [comment]
@tangopapa I returned to this issue today and found a workable solution (at least for a dev server). What I did was add a "listener" stanza to the vault local config, to extend your example:
`docker run --cap-add=IPC_LOCK
-e 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h", "listener": {"tcp": {"address": "127.0.0.1:8200", "tls_disable": "true"}}}'`
Note that last part, **"listener": {"tcp": {"address": "127.0.0.1:8200", "tls_disable": "true"}}**

After that I used docker to create a terminal session in the vault container, then I set the vault address, i.e. `export VAULT_ADDR=http://127.0.0.1:8200`, then I ran `vault init`, and now I'm able to use vault:
![image](https://user-images.githubusercontent.com/1503131/35688586-7ef38334-073f-11e8-94c9-88614d24d84c.png)
