### ISSUE TITLE
Vault docker image not starting

### ISSUE THREAD

**Issue by dabump** [hashicorp/docker-vault#77]
Heya guys!

Any ideas on what's wrong?

I pulled the latest version of vault from dockerhub, and get the following error when starting:

> Failed to set capabilities on file `/bin/vault' (Not supported)
> usage: setcap [-q] [-v] (-r|-|<caps>) <filename> [ ... (-r|-|<capsN>) <filenameN> ]
>
> Note <filename> must be a regular (non-symlink) file.

Here is my docker info
> root  ~  docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 115
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.74-2-MANJARO
Operating System: Manjaro Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.53GiB
Name: pc
ID: QDTM:RESB:ZLFA:BVS7:2RSH:IUOD:VOU6:NH2B:NIMU:P3BU:WM3E:KSYJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username:
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 10.1.135.10:5000
 127.0.0.0/8
Live Restore Enabled: false

**Comment by dabump** [comment]
My run command:
> docker run --cap-add=IPC_LOCK -d --name=dev-vault vault

**Comment by chrishoffman** [comment]
The aufs storage driver does not support setcap. Try the overlayfs driver. See #19.

**Comment by dabump** [comment]
Thanks Chris Hoffman. I can confirm that changing the underlying storage driver to overlay2, worked perfectly. I used the following steps to change to overlay2 driver, for the benefit of the people having the same issue in the future:

https://docs.docker.com/storage/storagedriver/overlayfs-driver/#configure-docker-with-the-overlay-or-overlay2-storage-driver
