### ISSUE TITLE
Cannot use image directly for HA in docker

### ISSUE THREAD

**Issue by skaczor** [hashicorp/docker-vault#8]
When running in docker, there is no way to anticipate the IP address of the container until the entry point is executed. When redirect and cluster addresses are left unspecified, the discovery process fails and the wrong IP address it used.

The only solution I see is to create organization's own image based on this image that sets the IP address in the entry point. I would rather avoid doing that.

A proposed solution is to provide the name of the network adapter that is accessible to other nodes using an environment variable, such as VAULT_CLUSTER_INTERFACE and VAULT_REDIRECT_INTERFACE. This is the way consul works with the CONSUL_BIND_INTERFACE AND CONSUL_CLIENT_INTERFACE environment variables.

**Comment by skaczor** [comment]
Here is my solution, would be nice if the wrapper script's functionality could be incorporated in the base image.

```
#!/bin/dumb-init /bin/sh
set -e

get_addr () {
    IF_NAME=$1
    ip addr show dev $IF_NAME | awk -v uri=$2 '/\s*inet\s/ { \
      ip=gensub(/(.+)\/.+/, "\\1", "g", $2); \
      print gensub(/^(.+:\/\/).+(:.+)$/, "\\1" ip "\\2", "g", uri)}'
}

if [ -n "$VAULT_REDIRECT_INTERFACE" ]; then
    export VAULT_REDIRECT_ADDR=$(get_addr $VAULT_REDIRECT_INTERFACE ${VAULT_REDIRECT_ADDR:-"http://0.0.0.0:8200"})
    echo "Setting VAULT_REDIRECT_ADDR=$VAULT_REDIRECT_ADDR"
fi
if [ -n "$VAULT_CLUSTER_INTERFACE" ]; then
    export VAULT_CLUSTER_ADDR=$(get_addr $VAULT_CLUSTER_INTERFACE ${VAULT_CLUSTER_ADDR:-"https://0.0.0.0:8201"})
    echo "Setting VAULT_CLUSTER_ADDR=$VAULT_CLUSTER_ADDR"
fi

. /usr/local/bin/docker-entrypoint.sh $@
```

**Comment by jefferai** [comment]
Any chance you can PR something?
