### ISSUE TITLE
No `0.9.5` Image

### ISSUE THREAD

**Issue by gargath** [hashicorp/docker-vault#80]
https://hub.docker.com/r/library/vault/tags/ does not seem to have an image for `0.9.5` even though https://hub.docker.com/r/library/vault/ lists 0.9.5 as latest.

`0.9.5` fixes https://github.com/hashicorp/vault/issues/4014 which is critical for us.
Any chance to get an image built?

**Comment by jefferai** [comment]
It's already been submitted yesterday, just waiting on Docker to accept it. You can always build straight from the Dockerfile if you want.
