### ISSUE TITLE
executable file not found in $PATH"

### ISSUE THREAD

**Issue by jpleban** [hashicorp/docker-vault#81]
Build the image from the Dockerfile.
Getting error below when ran the command:
"docker run --cap-add=IPC_LOCK -e 'VAULT_DEV_ROOT_TOKEN_ID=myroot' -e 'VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:1234' vault"

Error:
/usr/local/bin/docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown

**Comment by chrishoffman** [comment]
How are creating your Docker image and on what platform?  I am able to build and use the your command to launch the container without a problem.

**Comment by coconup** [comment]
I had the same issue just now, the problem is `docker-entrypoint.sh` is not executable when cloning the repo. This should probably be handled in the Dockerfile anyway:

```
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
```

**Comment by chrishoffman** [comment]
The file is executable if it is cloned so I am guessing using the download button and unzipping is losing the mode.
