### ISSUE TITLE
--cap-add=IPC_LOCK unavailable in docker swarm 

### ISSUE THREAD

**Issue by andrewhart098** [hashicorp/docker-vault#89]
In the documentation for the vault container, it states..

> The container will attempt to lock memory to prevent sensitive values from being swapped to disk and as a result must have --cap-add=IPC_LOCK provided to docker run.

I'm trying to run the vault container in a docker swarm. I'm running into the problem that the `cap-add` functionality is not available for docker swarm. See [this issue](https://github.com/moby/moby/issues/25885).

While there is some talk on a [potential solution](https://github.com/moby/moby/issues/32801) that would address, among other things, the missing cap-add functionality in docker swarm, I was wondering if you could provide some guidance as to a method of running vault within a docker swarm. Thanks!

**Comment by jefferai** [comment]
Simply disable mlock and you won't need the capability added.

**Comment by andrewhart098** [comment]
Thanks for the response.

I was hoping to find a solution that was production grade, any suggestions?

**Comment by jefferai** [comment]
I don't have any suggestions for you, other than a slightly :trollface: note that perhaps if Swarm doesn't support --cap-add (which has been in normal Docker forever), it itself isn't production grade? So perhaps if you overlooked that requirement in Swarm, you can overlook disabling mlock for now with Vault :-D
